DapperCvApp.UI/Areas/Admin/Controllers/CertificationController.cs
using AutoMapper;
using DapperCvApp.Business;
using DapperCvApp.DTO;
using DapperCvApp.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DapperCvApp.UI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class CertificationController : Controller
    {
        private readonly ICertificationService _certificationService;
        private readonly IMapper _mapper;

        public CertificationController(ICertificationService certificationService, IMapper mapper)
        {
            _certificationService = certificationService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            TempData["active"] = "Sertifika";
            IEnumerable<Certification> certification = await _certificationService.GetActiveAsync();

            List<CertificationListDto> certificationListDto = _mapper.Map<List<CertificationListDto>>(certification.ToList());

            return View(certificationListDto);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            Certification deletedCetification = await _certificationService.GetByIdAsync(id);
            bool isDeleted= _certificationService.Delete(deletedCetification);

            if (isDeleted)
                TempData["messageSuccess"] = "Silme işlemi Başarılı.";
            else
                TempData["messageError"] = "Silme işlemi Başarısız.";

            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult Save()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Save(CertificationAddDto certificationAddDto)
        {
            TempData["active"] = "Sertifika";

            if (!ModelState.IsValid)
                return View(certificationAddDto);

            Certification cetification = _mapper.Map<Certification>(certificationAddDto);
            int addedCertification = await _certificationService.InsertAsync(cetification);

            if (addedCertification>0)
                TempData["messageSuccess"] = "Ekleme işlemi Başarılı.";
            else
                TempData["messageError"] = "Ekleme işlemi Başarısız.";

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            TempData["active"] = "Sertifika";

            return View(_mapper.Map<CertificationUpdateDto>(await _certificationService.GetByIdAsync(id)));
        }

        [HttpPost]
        public async Task<IActionResult> Update(CertificationUpdateDto certificationUpdateDto)
        {
            TempData["active"] = "Sertifika";

            if (!ModelState.IsValid)
                return View(certificationUpdateDto);

            Certification certification = _mapper.Map<Certification>(certificationUpdateDto);
            bool isUpdated = await _certificationService.UpdateAsync(certification);

            if (isUpdated)
                TempData["messageSuccess"] = "Güncelleme işlemi Başarılı.";
            else
                TempData["messageError"] = "Güncelleme işlemi Başarısız.";

            return RedirectToAction("Index");
        }
    }
}

DapperCvApp.UI/Areas/Admin/Controllers/EducationController.cs
using AutoMapper;
using DapperCvApp.Business;
using DapperCvApp.DTO;
using DapperCvApp.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DapperCvApp.UI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles="Admin")]
    public class EducationController : Controller
    {
        private readonly IEducationService _educationService;
        private readonly IMapper _mapper;

        public EducationController(IEducationService educationService, IMapper mapper)
        {
            _educationService = educationService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            TempData["active"] = "egitim";
            IEnumerable<Education> education = await _educationService.GetActiveAsync();

            List<EducationListDto> educationListDto =_mapper.Map<List<EducationListDto>>(education.ToList());

            return View(educationListDto);
        }

        [HttpGet]
        public IActionResult Save()
        {
            TempData["active"] = "egitim";
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Save(EducationAddDto educationAddDto)
        {
            TempData["active"] = "egitim";
            if (!ModelState.IsValid)
                return View(educationAddDto);

            Education education = _mapper.Map<Education>(educationAddDto);
            int addedEducation = await _educationService.InsertAsync(education);

            if (addedEducation>0)
                TempData["messageSucces"] = "Egitim bilgileri Eklendi.";
            else
                TempData["messageError"] = "Egitim bilgileri Ekleme işlemi BAŞARISIZ!!!";

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            TempData["active"] = "egitim";

            Education education =await _educationService.GetByIdAsync(id);
            EducationUpdateDto educationUpdateDto=_mapper.Map<EducationUpdateDto>(education);

            return View(educationUpdateDto);
        }

        [HttpPost]
        public async Task<IActionResult> Update(EducationUpdateDto educationUpdateDto)
        {
            TempData["active"] = "egitim";

            if (!ModelState.IsValid)
                return View(educationUpdateDto);

            var education=_mapper.Map<Education>(educationUpdateDto);
            bool isUpdated = await _educationService.UpdateAsync(education);

            if (isUpdated)
                TempData["messageSuccess"] = "Güncelleme işlemi Başarılı.";
            else
                TempData["messageError"] = "Güncelleme işlemi BAŞARISIZ!!!";


            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            Education education = await _educationService.GetByIdAsync(id);
            bool isDeleted=_educationService.Delete(education);

            if (isDeleted)
                TempData["messageSuccess"] = "Slime işlemi Başarılı.";
            else
                TempData["messageError"] = "Silme işlemi BAŞARISIZ!!!";

            return RedirectToAction("Index");
        }




    }
}

DapperCvApp.UI/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Simple Sidebar - Start Bootstrap Template</title>

    <!-- Bootstrap core CSS -->
    <link href="/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/css/simple-sidebar.css" rel="stylesheet">

</head>

<body>

    <div class="d-flex" id="wrapper">

        <!-- Sidebar -->
        <div class="bg-light border-right" id="sidebar-wrapper">
            <div class="sidebar-heading">Start Bootstrap </div>
            <div class="list-group list-group-flush">
                <a asp-action="Index" asp-controller="Home" asp-area="Admin" class="list-group-item list-group-item-action @(TempData["active"]?.ToString()=="Bilgilerim"?"active":"")">Bilgilerim</a>
                <a asp-action="ChangePassword" asp-controller="Home" asp-area="Admin" class="list-group-item list-group-item-action @(TempData["active"]?.ToString()=="Şifre"?"active":"")">Şifre Degiştir</a>
                <a asp-action="Index" asp-controller="Certification" asp-area="Admin" class="list-group-item list-group-item-action @(TempData["active"]?.ToString()=="Sertifika"?"active":"")">Sertifikalar</a>
                <a asp-action="Index" asp-controller="Education" asp-area="Admin" class="list-group-item list-group-item-action @(TempData["active"]?.ToString()=="egitim"?"active":"")">Egitim bilgileri</a>
            </div>
        </div>
        <!-- /#sidebar-wrapper -->
        <!-- Page Content -->
        <div id="page-content-wrapper">

            <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                <button class="btn btn-primary" id="menu-toggle">Menü</button>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
                       @* <li class="nav-item active"><a class="nav-link" href="#!">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">Link</a></li>*@
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="#!">Action</a>
                                <a class="dropdown-item" href="#!">Another action</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#!">Something else here</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>

            <div class="container-fluid p-3">
                
                @{
                    if (TempData["messageSuccess"]?.ToString() != null)
                    {
                        <div class="alert alert-info alert-dismissible fade show my-2" role="alert">
                            @TempData["messageSuccess"].ToString()
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    }
                    else if (TempData["messageError"]?.ToString()  != null)
                    {
                        <div class="alert alert-info alert-dismissible fade show my-2" role="alert">
                            @TempData["messageError"].ToString()
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    }

                }
                @RenderBody()
            </div>
        </div>


        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->
    <!-- Bootstrap core JavaScript -->
    <script src="~/jquery/jquery.min.js"></script>
    <script src="~/twitter-bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Menu Toggle Script -->
    <script>
        $("#menu-toggle").click(function(e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });</script>

</body>

</html>